version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: .
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - /root/secrets/traxkick.env

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
    depends_on:
      - backend
    restart: always